sudo: required
dist: bionic
language: java
services:
- docker
jdk:
- openjdk11
env:
  global:
  - DOCKER_IMAGE=bcesnik/rso-image-catalog:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: p/DNltpAlreRM3XKJyvDMQx94apOW8LUeGGRpIcEb4s3dTWPRMjdZlvlu5nLwnXNFpUMuYP+tYpN3dtKIO3I8vuwLE2OilcVKGYYpn24d0L89GFWFOJYmGTYD25VNxuN9jdeoLNrrCIBVazTclHiI3slhW/kPb9+HjBOunkhKeAoBh4tsRhsxMpyrRXeHQG+2DYaZ3J9nH+GH+tMbZabjfy3aiLPkKlMghnDp/GpX2XHGysdvZiNnFqUW2p3UNDIXmuqJlEmLbzUb++VpDAAxgdHx0lrrUTv4W9uyGXzyGr4QI2ZkSp467wqxJ1GdyuScrUp/hyj9AwtghMg+vS4NtpoaxGJgrpthVEJautT+8Aqt+x1JNv05Du1dvb1aVH2dDGzVl3kPf/D85ZzS4cHqNjbSMy0N84YgGZ9LuSKBjOcOX6qVdjiqZu/SiCVQdgPh377FfZ+RH4YKXj470Dv0OIqc7PnfLAe9cS1CwDo700cVrBa2OqAZd/pDcS6OpzhsE7IYVpX2aEpg2ecNDriGgQUfMNeU4zowtMa/r6tUDqqqSm12vzR3uUYlowGdZnx+sm2vtnl3LAJBl4HB0NHCCc6+8LFyx0euB+HqNuAVrYJq+ATbzUceCKaiuLxb9tTePWSKq8n3vSj0ht4Kp9LGuP06frmhEL+uaxf0SZRGKY=
  - secure: C8q762gddgpHMUGcaqYEslbvMMpzlBfFs4ZINyKTIRKQxeMG3zRT3Y5qS3yLYzTATZRsLQhzUm/7IDsL4W83RH14IQTOktDZe/PYI1BmP+Fp0kIZYlHjxkvOPBVmv2/Pc0pKNt3BxyIOKECqMWHFbeoGVULOtoi1Gx47qd4MtW5Atv6oSlgR7ZRq2VD33Zw4VMA0iXxAzLQSwESshLkH2DAUdUgI3M3QglIz0ANVMmnrdjhUv25Qf2orG0voIBbExs9IN+E61zbqPltB4Y6Tc+JfFpU6ExjkClv5cdwqsfEIn4c7SbC1GQyTHHJPGmajMBywhEn8YTclj03cFKbnx7dQCSGbOdVLa3UGghDfVMURqJFfMaLhxRAfCUoFndRf/DJ0MWCitThkmKWUhxEp1Gpobj1nLu8olkVC87W1QdHWRbRIxHVDgbB2fNhok/QECBthPAE5VMJ6NhBYZcbNQSD2DiWHUp1cI9juhj5i/+kKomF0wFLYeMTa+eOMIdYgdMr40V0u9NQnZOOQCENrQHfK9n/l4JII/2WlVR0JXYE71VztmPrU8bKVxO14rNeoesnzEeMmWoKpnTS9iScHvwsefxhqgbcmg3RHIcIU005v5qCxqFcuLwhGGJKt5nwPcN6PilpES2gL0GIXbvtMJl5iin1B4kywOUH/gFyIohY=
cache:
  directories:
  - "$HOME/.m2"
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
