kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/ImageDS
      connection-url: jdbc:postgresql://35.205.56.107:5432/images_db
      username: postgres
      password: adminadmin
      pool:
        max-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
    discovery:
      etcd:
        hosts: http://localhost:2379